### ISSUE TITLE
git action workflows  처리 관련 전달사항 

### ISSUE THREAD

**Issue by whl5105** [ad-earth/client-v2.0#56]
### **1.refac and fix 브랜치 작업전 refactoring branch pull** 
- refac 또는 fix 브랜치에 deploy.yml파일이 없으므로 추후 작업시 꼭  refactoring branch pull 후 작업해주시기 바랍니다.   

### **2.main push -> main  pull_request closed 후 action 처리 변경** 

```
on:
  pull_request:
    branches:
      - main
    types: [closed]
```

### **3.environment: production 환경 보호규칙 추가 설정** 

- pr colsed 후 수동 승인 처리로 배포환경 규칙 추가 
- 승인 후 deploy-production 실행 

```
jobs:
  deploy-production:
    name: Deploy(Production)
    runs-on: ubuntu-latest
    environment: production
```

<img width="879" alt="image" src="https://user-images.githubusercontent.com/73993670/229433492-9829eb05-bca3-4995-bdee-4a17a00842f0.png">
